api_version = "2026-01"

[[extensions]]
type = "ui_extension"
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
uid = "d3297932-462f-7d27-e4cd-2a86c5005fea2dbdc818"
handle = "viva-wallet"
description = "Accept Viva Wallet terminal payments directly in Shopify POS."

# module: file that contains your extension’s source code
# target: location where your extension appears in POS
[[extensions.targeting]]
module = "./src/Tile.jsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.jsx"
target = "pos.home.modal.render"

[extensions.capabilities]
network_access = true